### ISSUE TITLE
Mobs should move when you bump into things, or we need another way to wait

### ISSUE THREAD

**Issue by singalen** [ondras/sleeping-beauty#6]
Now I'm blocked by a fellow adventurer in a niche:
```
###
#@#
.a.
```
There's no way to wait till they move, either by moving or Enter or shift-arrows.

**Comment by ondras** [comment]
Hi @singalen ,

thanks for the report; `spacebar` now skips a turn.

**Comment by singalen** [comment]
Well, kissing the knight worked in the end... :D
